coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 2%
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "**/__pycache__"
  - "**/*.pyc"
  - "**/__main__.py"
